name: Java CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download JUnit 5 Console Launcher
        run: |
          mkdir -p lib
          curl -L -o lib/junit-platform-console-standalone-1.9.3.jar \
            https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

      - name: Compile Java files from src/
        run: |
          mkdir -p out
          find src -type f -name "*.java" > sources.txt
          javac -cp lib/junit-platform-console-standalone-1.9.3.jar -d out @sources.txt


      - name: Run tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.9.3.jar \
            --classpath out \
            --scan-class-path
